#!/usr/bin/php
<?php

$binary = __DIR__ . '/../PHPInterp';

$dirit = new RecursiveDirectoryIterator('.');
$it = new RecursiveIteratorIterator($dirit);

foreach($it as $file) {
      if (!preg_match('/.php$/', $file->getFilename()))
          continue;

    $filepath = $file->getPath() . '/' . $file->getFilename();
    echo "FILE: ", $file->getFilename(), PHP_EOL;
    echo "=================================", PHP_EOL;
    $out = substr($file->getRealpath(), 0, -4) . '.out';
    $expect = substr($file->getRealpath(), 0, -4) . '.expect';
    system($binary . ' '. escapeshellarg($filepath) . ' > ' . escapeshellarg($out));
    $ret = null;
    system('diff -u ' . escapeshellarg($out) . ' ' . escapeshellarg($expect), $ret);
    if ($ret !== 0) {
      echo error("ERROR");
    } else {
      echo success("SUCCESS");
    }
    echo PHP_EOL;
}

function error($str) {
  return "\e[1m\e[31m$str\e[0m";
}

function success($str) {
  return "\e[32m\e[1m$str\e[0m";
}
