#!/usr/bin/php
<?php

$dirit = new RecursiveDirectoryIterator(__DIR__);
$it = new RecursiveIteratorIterator($dirit);

foreach($it as $file) {
    if (in_array($file->getFilename(), ['run', '.', '..'])) 
        continue;

    echo "FILE: ", $file->getFilename(), PHP_EOL;
    echo "=================================", PHP_EOL;
    system(__DIR__ . '/../PHPInterp ' . escapeshellarg($file->getRealPath()));
    echo PHP_EOL;
}
